name: Android APK Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu Cek
      uses: actions/checkout@v4

    - name: Java 17 Kur
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle Kur
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.1.1

    - name: APK Derle
      # Projende gradlew olmadığı için kurduğumuz gradle ile derliyoruz
      run: gradle assembleDebug

    - name: APK Dosyasini Yukle
      uses: actions/upload-artifact@v4
      with:
        name: BordroApp-Yukle
        path: app/build/outputs/apk/debug/app-debug.apk